/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design_test;

/**
 *
 * @author Laurent
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        contentView = new javax.swing.JPanel();
        Court_A1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        img_courtA1 = new javax.swing.JLabel();
        name_courtA1 = new javax.swing.JLabel();
        vs_courtA1 = new javax.swing.JLabel();
        Court_A = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        img_courtA = new javax.swing.JLabel();
        name_courtA = new javax.swing.JLabel();
        vs_courtA = new javax.swing.JLabel();
        Court_A2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        img_courtA2 = new javax.swing.JLabel();
        name_courtA2 = new javax.swing.JLabel();
        vs_courtA2 = new javax.swing.JLabel();
        Court_A3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        img_courtA3 = new javax.swing.JLabel();
        name_courtA3 = new javax.swing.JLabel();
        vs_courtA3 = new javax.swing.JLabel();
        Court_A4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        img_courtA4 = new javax.swing.JLabel();
        name_courtA4 = new javax.swing.JLabel();
        vs_courtA4 = new javax.swing.JLabel();
        Court_A5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        img_courtA5 = new javax.swing.JLabel();
        name_courtA5 = new javax.swing.JLabel();
        vs_courtA5 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des courts");
        setLocation(null);
        setResizable(false);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel5);

        contentView.setToolTipText("");
        contentView.setLayout(new java.awt.GridLayout(2, 3));

        Court_A1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>ROUQ/MORE<br>JEAN/MI-J<br>Arbitre : ABCD</html>");
        jPanel6.add(jLabel3, java.awt.BorderLayout.CENTER);

        Court_A1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 90));

        img_courtA1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_courtA1.setForeground(new java.awt.Color(91, 135, 125));
        img_courtA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_large.jpg"))); // NOI18N
        img_courtA1.setText("■");
        img_courtA1.setToolTipText("");
        Court_A1.add(img_courtA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        name_courtA1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name_courtA1.setText("Court central");
        Court_A1.add(name_courtA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        vs_courtA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_courtA1.setText("Qualification");
        Court_A1.add(vs_courtA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, -1));

        contentView.add(Court_A1);

        Court_A.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>ROUQ/MORE<br>JEAN/MI-J<br>Arbitre : ABCD</html>");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        Court_A.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 90));

        img_courtA.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_courtA.setForeground(new java.awt.Color(91, 135, 125));
        img_courtA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_large.jpg"))); // NOI18N
        img_courtA.setText("■");
        img_courtA.setToolTipText("");
        Court_A.add(img_courtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        name_courtA.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name_courtA.setText("Court central");
        Court_A.add(name_courtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        vs_courtA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_courtA.setText("Qualification");
        Court_A.add(vs_courtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, -1));

        contentView.add(Court_A);

        Court_A2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>ROUQ/MORE<br>JEAN/MI-J<br>Arbitre : ABCD</html>");
        jPanel7.add(jLabel4, java.awt.BorderLayout.CENTER);

        Court_A2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 90));

        img_courtA2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_courtA2.setForeground(new java.awt.Color(91, 135, 125));
        img_courtA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_large.jpg"))); // NOI18N
        img_courtA2.setText("■");
        img_courtA2.setToolTipText("");
        Court_A2.add(img_courtA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        name_courtA2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name_courtA2.setText("Court central");
        Court_A2.add(name_courtA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        vs_courtA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_courtA2.setText("Qualification");
        Court_A2.add(vs_courtA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, -1));

        contentView.add(Court_A2);

        Court_A3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>ROUQ/MORE<br>JEAN/MI-J<br>Arbitre : ABCD</html>");
        jPanel8.add(jLabel5, java.awt.BorderLayout.CENTER);

        Court_A3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 90));

        img_courtA3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_courtA3.setForeground(new java.awt.Color(91, 135, 125));
        img_courtA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_large.jpg"))); // NOI18N
        img_courtA3.setText("■");
        img_courtA3.setToolTipText("");
        Court_A3.add(img_courtA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        name_courtA3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name_courtA3.setText("Court central");
        Court_A3.add(name_courtA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        vs_courtA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_courtA3.setText("Qualification");
        Court_A3.add(vs_courtA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, -1));

        contentView.add(Court_A3);

        Court_A4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html>ROUQ/MORE<br>JEAN/MI-J<br>Arbitre : ABCD</html>");
        jPanel9.add(jLabel6, java.awt.BorderLayout.CENTER);

        Court_A4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 90));

        img_courtA4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_courtA4.setForeground(new java.awt.Color(91, 135, 125));
        img_courtA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_large.jpg"))); // NOI18N
        img_courtA4.setText("■");
        img_courtA4.setToolTipText("");
        Court_A4.add(img_courtA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        name_courtA4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name_courtA4.setText("Court central");
        Court_A4.add(name_courtA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        vs_courtA4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_courtA4.setText("Qualification");
        Court_A4.add(vs_courtA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, -1));

        contentView.add(Court_A4);

        Court_A5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>ROUQ/MORE<br>JEAN/MI-J<br>Arbitre : ABCD</html>");
        jPanel10.add(jLabel7, java.awt.BorderLayout.CENTER);

        Court_A5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 140, 90));

        img_courtA5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_courtA5.setForeground(new java.awt.Color(91, 135, 125));
        img_courtA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_large.jpg"))); // NOI18N
        img_courtA5.setText("■");
        img_courtA5.setToolTipText("");
        Court_A5.add(img_courtA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        name_courtA5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name_courtA5.setText("Court central");
        Court_A5.add(name_courtA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        vs_courtA5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_courtA5.setText("Qualification");
        Court_A5.add(vs_courtA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, -1));

        contentView.add(Court_A5);

        jTabbedPane2.addTab("8h", contentView);

        jTabbedPane1.addTab("Jour 1", jTabbedPane2);

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.addTab("tab2", jTabbedPane3);
        jTabbedPane1.addTab("tab2", jTabbedPane4);
        jTabbedPane1.addTab("tab2", jTabbedPane5);
        jTabbedPane1.addTab("tab2", jTabbedPane6);
        jTabbedPane1.addTab("tab2", jTabbedPane7);
        jTabbedPane1.addTab("tab2", jTabbedPane8);
        jTabbedPane1.addTab("tab2", jTabbedPane9);
        jTabbedPane1.addTab("tab2", jTabbedPane10);

        jMenu1.setText("Générer les qualifications");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Court_A;
    private javax.swing.JPanel Court_A1;
    private javax.swing.JPanel Court_A2;
    private javax.swing.JPanel Court_A3;
    private javax.swing.JPanel Court_A4;
    private javax.swing.JPanel Court_A5;
    private javax.swing.JPanel contentView;
    private javax.swing.JLabel img_courtA;
    private javax.swing.JLabel img_courtA1;
    private javax.swing.JLabel img_courtA2;
    private javax.swing.JLabel img_courtA3;
    private javax.swing.JLabel img_courtA4;
    private javax.swing.JLabel img_courtA5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    private javax.swing.JLabel name_courtA;
    private javax.swing.JLabel name_courtA1;
    private javax.swing.JLabel name_courtA2;
    private javax.swing.JLabel name_courtA3;
    private javax.swing.JLabel name_courtA4;
    private javax.swing.JLabel name_courtA5;
    private javax.swing.JLabel vs_courtA;
    private javax.swing.JLabel vs_courtA1;
    private javax.swing.JLabel vs_courtA2;
    private javax.swing.JLabel vs_courtA3;
    private javax.swing.JLabel vs_courtA4;
    private javax.swing.JLabel vs_courtA5;
    // End of variables declaration//GEN-END:variables
}
