/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Laurent
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        contentView = new javax.swing.JPanel();
        img_courtA = new javax.swing.JLabel();
        img_courtB = new javax.swing.JLabel();
        name_courtA = new javax.swing.JLabel();
        name_courtB = new javax.swing.JLabel();
        img_train1 = new javax.swing.JLabel();
        name_train1 = new javax.swing.JLabel();
        img_train2 = new javax.swing.JLabel();
        name_train2 = new javax.swing.JLabel();
        name_train3 = new javax.swing.JLabel();
        img_train3 = new javax.swing.JLabel();
        vs_courtA = new javax.swing.JLabel();
        vs_courtB = new javax.swing.JLabel();
        vs_train1 = new javax.swing.JLabel();
        vs_train2 = new javax.swing.JLabel();
        vs_train3 = new javax.swing.JLabel();
        img_train4 = new javax.swing.JLabel();
        vs_train4 = new javax.swing.JLabel();
        name_train4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jTabbedPane10 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des courts");
        setLocation(null);
        setResizable(false);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        contentView.setToolTipText("");

        img_courtA.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_courtA.setForeground(new java.awt.Color(91, 135, 125));
        img_courtA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_large.jpg"))); // NOI18N
        img_courtA.setText("■");
        img_courtA.setToolTipText("");

        img_courtB.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_courtB.setForeground(new java.awt.Color(149, 44, 40));
        img_courtB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_large.jpg"))); // NOI18N
        img_courtB.setText("■");
        img_courtB.setToolTipText("");

        name_courtA.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name_courtA.setText("Court central");

        name_courtB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name_courtB.setText("Court secondaire");

        img_train1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_train1.setForeground(new java.awt.Color(91, 135, 125));
        img_train1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_small.jpg"))); // NOI18N
        img_train1.setText("■");
        img_train1.setToolTipText("");

        name_train1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name_train1.setText("Entraînement A");

        img_train2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_train2.setForeground(new java.awt.Color(206, 117, 103));
        img_train2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_small.jpg"))); // NOI18N
        img_train2.setText("■");
        img_train2.setToolTipText("");

        name_train2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name_train2.setText("Entraînement B");

        name_train3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name_train3.setText("Entraînement C");

        img_train3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_train3.setForeground(new java.awt.Color(91, 135, 125));
        img_train3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_small.jpg"))); // NOI18N
        img_train3.setText("■");
        img_train3.setToolTipText("");

        vs_courtA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_courtA.setText("Libre");

        vs_courtB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_courtB.setText("Laurent MOREL vs Loïc ROUQUETTE");

        vs_train1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_train1.setText("Libre");

        vs_train2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_train2.setText("Libre");

        vs_train3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_train3.setText("Libre");

        img_train4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        img_train4.setForeground(new java.awt.Color(91, 135, 125));
        img_train4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/court_small.jpg"))); // NOI18N
        img_train4.setText("■");
        img_train4.setToolTipText("");

        vs_train4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs_train4.setText("Libre");

        name_train4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name_train4.setText("Entraînement C");

        javax.swing.GroupLayout contentViewLayout = new javax.swing.GroupLayout(contentView);
        contentView.setLayout(contentViewLayout);
        contentViewLayout.setHorizontalGroup(
            contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentViewLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vs_courtB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentViewLayout.createSequentialGroup()
                        .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img_courtB)
                            .addGroup(contentViewLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(name_courtB))
                            .addGroup(contentViewLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(name_courtA))
                            .addComponent(img_courtA)
                            .addComponent(vs_courtA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentViewLayout.createSequentialGroup()
                                .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(img_train2)
                                        .addGroup(contentViewLayout.createSequentialGroup()
                                            .addComponent(name_train2)
                                            .addGap(59, 59, 59)))
                                    .addComponent(vs_train2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vs_train4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(img_train4)
                                        .addGroup(contentViewLayout.createSequentialGroup()
                                            .addComponent(name_train4)
                                            .addGap(59, 59, 59)))))
                            .addGroup(contentViewLayout.createSequentialGroup()
                                .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentViewLayout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addComponent(name_train1)
                                            .addGap(55, 55, 55))
                                        .addComponent(img_train1))
                                    .addComponent(vs_train1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vs_train3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(img_train3)
                                        .addGroup(contentViewLayout.createSequentialGroup()
                                            .addComponent(name_train3)
                                            .addGap(59, 59, 59))))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        contentViewLayout.setVerticalGroup(
            contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentViewLayout.createSequentialGroup()
                .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentViewLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(name_courtA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img_courtA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vs_courtA)
                        .addGap(18, 18, 18)
                        .addComponent(name_courtB))
                    .addGroup(contentViewLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentViewLayout.createSequentialGroup()
                                .addComponent(name_train1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(img_train1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vs_train1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentViewLayout.createSequentialGroup()
                                .addComponent(name_train3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(img_train3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vs_train3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentViewLayout.createSequentialGroup()
                        .addComponent(name_train2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img_train2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vs_train2))
                    .addGroup(contentViewLayout.createSequentialGroup()
                        .addComponent(name_train4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img_train4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vs_train4))
                    .addGroup(contentViewLayout.createSequentialGroup()
                        .addComponent(img_courtB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vs_courtB)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("8h", contentView);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel5);

        jTabbedPane1.addTab("Jour 1", jTabbedPane2);

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.addTab("tab2", jTabbedPane3);
        jTabbedPane1.addTab("tab2", jTabbedPane4);
        jTabbedPane1.addTab("tab2", jTabbedPane5);
        jTabbedPane1.addTab("tab2", jTabbedPane6);
        jTabbedPane1.addTab("tab2", jTabbedPane7);
        jTabbedPane1.addTab("tab2", jTabbedPane8);
        jTabbedPane1.addTab("tab2", jTabbedPane9);
        jTabbedPane1.addTab("tab2", jTabbedPane10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentView;
    private javax.swing.JLabel img_courtA;
    private javax.swing.JLabel img_courtB;
    private javax.swing.JLabel img_train1;
    private javax.swing.JLabel img_train2;
    private javax.swing.JLabel img_train3;
    private javax.swing.JLabel img_train4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    private javax.swing.JLabel name_courtA;
    private javax.swing.JLabel name_courtB;
    private javax.swing.JLabel name_train1;
    private javax.swing.JLabel name_train2;
    private javax.swing.JLabel name_train3;
    private javax.swing.JLabel name_train4;
    private javax.swing.JLabel vs_courtA;
    private javax.swing.JLabel vs_courtB;
    private javax.swing.JLabel vs_train1;
    private javax.swing.JLabel vs_train2;
    private javax.swing.JLabel vs_train3;
    private javax.swing.JLabel vs_train4;
    // End of variables declaration//GEN-END:variables
}
